
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const source = await readFile(new URL("./_worker.js", import.meta.url), "utf8");
const worker = (await import("data:text/javascript;base64," + Buffer.from(source).toString("base64"))).default;
let calls = [];
let reply;
globalThis.fetch = async (request, options) => {
  calls.push({ request, options });
  return reply();
};
const invoke = (path, init={}) => worker.fetch(new Request("https://reazromen.com"+path, init), {});
let r = await invoke("/admin?from=menu");
assert.equal(r.status,308);
assert.equal(r.headers.get("Location"),"https://reazromen.com/admin/?from=menu");
assert.equal(calls.length,0);
reply = () => new Response("login", {status:401,headers:{Location:"https://auth.reazromen.com/?rd="+encodeURIComponent("https://studio.reazromen.com/admin/")+"&rm=GET"}});
r=await invoke("/admin/",{headers:{Accept:"text/html"}});
assert.equal(r.status,302);
assert.equal(new URL(r.headers.get("Location")).searchParams.get("rd"),"https://reazromen.com/admin/");
assert.match(r.headers.get("Cache-Control"),/no-store/);
reply = () => new Response("login", {status:401,headers:{Location:"https://auth.reazromen.com/?rd="+encodeURIComponent("https://studio.reazromen.com/admin/api/v1")}});
r=await invoke("/admin/api/v1",{method:"POST",headers:{"Content-Type":"application/json"},body:'{"action":"info"}'});
assert.equal(r.status,401);
reply=()=>new Response('{"ok":true}',{headers:{"Content-Type":"application/json","Set-Cookie":"test=value; Secure; HttpOnly"}});
r=await invoke("/admin/api/v1?test=1",{method:"POST",headers:{"Content-Type":"application/json",Cookie:"test-session=fake",Origin:"https://reazromen.com"},body:'{"action":"info"}'});
const c=calls.at(-1);
assert.equal(c.request.url,"https://studio.reazromen.com/admin/api/v1?test=1");
assert.equal(c.request.method,"POST");
assert.equal(c.request.headers.get("Cookie"),"test-session=fake");
assert.equal(c.request.headers.get("Origin"),"https://reazromen.com");
assert.equal(await c.request.text(),'{"action":"info"}');
assert.equal(c.options.redirect,"manual");
assert.equal(c.options.cf.cacheTtlByStatus["100-599"],-1);
assert.equal(r.headers.get("Set-Cookie"),"test=value; Secure; HttpOnly");
assert.equal(await r.text(),'{"ok":true}');
reply=()=>new Response("denied",{status:403});
assert.equal((await invoke("/admin/config.yml")).status,403);
reply=()=>new Response(null,{status:308,headers:{Location:"https://studio.reazromen.com/admin/sub/" }});
assert.equal((await invoke("/admin/sub")).headers.get("Location"),"https://reazromen.com/admin/sub/");
reply=()=>new Response("<html>public</html>");
r=await invoke("/");
assert.equal(calls.at(-1).request.url,"https://reazromen.github.io/website/");
assert.equal(r.headers.get("X-Reaz-Delivery"),"github-pages-via-cloudflare-pages");
console.log("PASS: canonical URL, Authelia return, unauthenticated API denial, authenticated request forwarding, cookies, no caching, origin redirects, public route");
